[build]
  command = "npm run build"  # Adjust this if needed
  publish = "./"  # Points to the directory where static files are located

[[plugins]]
  package = "@netlify/plugin-functions-core"  # This is required for Netlify Functions
